"""Initial operational schema

Revision ID: e7d7ced9e260
Revises:
Create Date: 2026-05-31 12:16:56.240496

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7d7ced9e260"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refund_policies",
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("product_family", sa.Text(), nullable=False),
        sa.Column("all_sales_final", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("supersedes_version", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("policy_id", "policy_version", name=op.f("pk_refund_policies")),
    )
    op.create_table(
        "bookings",
        sa.Column("booking_id", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.String(length=32), nullable=False),
        sa.Column("product_family", sa.Text(), nullable=False),
        sa.Column("option_name", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("amount_paid_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("purchase_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("traveler_count", sa.Integer(), nullable=False),
        sa.Column("pinned_policy_id", sa.String(length=64), nullable=False),
        sa.Column("pinned_policy_version", sa.String(length=16), nullable=False),
        sa.Column("supplier_timezone", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "status IN ("
            "'CONFIRMED','PARTIALLY_CANCELLED','CANCELLED',"
            "'COMPLETED','REBOOKED','PENDING'"
            ")",
            name=op.f("ck_bookings_status_valid"),
        ),
        sa.CheckConstraint("amount_paid_minor >= 0", name=op.f("ck_bookings_amount_nonneg")),
        sa.CheckConstraint("start_ts > purchase_ts", name=op.f("ck_bookings_start_after_purchase")),
        sa.CheckConstraint("traveler_count >= 1", name=op.f("ck_bookings_traveler_count_positive")),
        sa.ForeignKeyConstraint(
            ["pinned_policy_id", "pinned_policy_version"],
            ["refund_policies.policy_id", "refund_policies.policy_version"],
            name=op.f("fk_bookings_pinned_policy_id_refund_policies"),
        ),
        sa.PrimaryKeyConstraint("booking_id", name=op.f("pk_bookings")),
    )
    op.create_index(op.f("ix_bookings_customer_id"), "bookings", ["customer_id"], unique=False)
    op.create_table(
        "refund_policy_tiers",
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("tier_order", sa.Integer(), nullable=False),
        sa.Column("min_hours_before_start", sa.Integer(), nullable=False),
        sa.Column("refund_pct", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "min_hours_before_start >= 0", name=op.f("ck_refund_policy_tiers_min_hours_nonneg")
        ),
        sa.CheckConstraint(
            "refund_pct BETWEEN 0 AND 100", name=op.f("ck_refund_policy_tiers_refund_pct_range")
        ),
        sa.CheckConstraint(
            "tier_order >= 1", name=op.f("ck_refund_policy_tiers_tier_order_positive")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id", "policy_version"],
            ["refund_policies.policy_id", "refund_policies.policy_version"],
            name=op.f("fk_refund_policy_tiers_policy_id_refund_policies"),
        ),
        sa.PrimaryKeyConstraint(
            "policy_id", "policy_version", "tier_order", name=op.f("pk_refund_policy_tiers")
        ),
    )
    op.create_table(
        "refund_requests",
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.String(length=32), nullable=False),
        sa.Column("requester_customer_id", sa.String(length=32), nullable=False),
        sa.Column("request_type", sa.String(length=24), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="OPEN", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "request_type IN ('CANCEL','PARTIAL_CANCEL','REBOOK','WEATHER_DISRUPTION','OTHER')",
            name=op.f("ck_refund_requests_request_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ("
            "'CONFIRMED','PARTIALLY_CANCELLED','CANCELLED',"
            "'COMPLETED','REBOOKED','PENDING'"
            ")",
            name=op.f("ck_bookings_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.booking_id"],
            name=op.f("fk_refund_requests_booking_id_bookings"),
        ),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_refund_requests")),
    )
    op.create_index(
        op.f("ix_refund_requests_booking_id"), "refund_requests", ["booking_id"], unique=False
    )
    op.create_table(
        "refund_decisions",
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.String(length=32), nullable=False),
        sa.Column("decision_kind", sa.String(length=24), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("applied_policy_id", sa.String(length=64), nullable=False),
        sa.Column("applied_policy_version", sa.String(length=16), nullable=False),
        sa.Column("covered_traveler_count", sa.Integer(), nullable=False),
        sa.Column("hours_before_start_at_decision", sa.Integer(), nullable=False),
        sa.Column("rebooked_to_booking_id", sa.String(length=32), nullable=True),
        sa.Column("confirmation_token", sa.String(length=64), nullable=False),
        sa.Column("decided_by", sa.String(length=32), server_default="agent", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision_kind IN ('FULL_REFUND','PARTIAL_REFUND','DENY','REBOOK_CREDIT')",
            name=op.f("ck_refund_decisions_decision_kind_valid"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_refund_decisions_amount_nonneg")),
        sa.CheckConstraint(
            "covered_traveler_count >= 0", name=op.f("ck_refund_decisions_covered_count_nonneg")
        ),
        sa.ForeignKeyConstraint(
            ["applied_policy_id", "applied_policy_version"],
            ["refund_policies.policy_id", "refund_policies.policy_version"],
            name=op.f("fk_refund_decisions_applied_policy_id_refund_policies"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.booking_id"],
            name=op.f("fk_refund_decisions_booking_id_bookings"),
        ),
        sa.ForeignKeyConstraint(
            ["rebooked_to_booking_id"],
            ["bookings.booking_id"],
            name=op.f("fk_refund_decisions_rebooked_to_booking_id_bookings"),
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["refund_requests.request_id"],
            name=op.f("fk_refund_decisions_request_id_refund_requests"),
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_refund_decisions")),
    )
    op.create_index(
        op.f("ix_refund_decisions_booking_id"), "refund_decisions", ["booking_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refund_decisions_booking_id"), table_name="refund_decisions")
    op.drop_table("refund_decisions")
    op.drop_index(op.f("ix_refund_requests_booking_id"), table_name="refund_requests")
    op.drop_table("refund_requests")
    op.drop_table("refund_policy_tiers")
    op.drop_index(op.f("ix_bookings_customer_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_table("refund_policies")
    # ### end Alembic commands ###
