# Tooling + provider pins. OpenTofu reads the `terraform {}` block name for
# backward compatibility, so this config runs unchanged on `tofu` or `terraform`.
#
# Why OpenTofu, not Terraform: Terraform moved to the BSL (source-available,
# non-OSS) at v1.6. OpenTofu is the Linux Foundation OSS fork and a drop-in CLI.
# OSS-first is the project's standing bias (see ADR-0004 when written).
terraform {
  required_version = ">= 1.8"

  required_providers {
    kind = {
      source  = "tehcyx/kind"
      version = ">= 0.2.0"
    }
  }
}

# The real pin is `.terraform.lock.hcl` (generated by `tofu init`, committed to
# the repo): it records the exact resolved version + checksums per platform. The
# constraint above is the floor; the lock file is the source of truth.
provider "kind" {}
